/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/meal-plans/{planId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get full meal plan with all days, meals, and food items */
        get: operations["get_1"];
        /** Update meal plan metadata */
        put: operations["update"];
        post?: never;
        /** Delete meal plan (soft delete) */
        delete: operations["delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meal-plans/{planId}/days/{dayId}/meals/{mealId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Update a meal */
        put: operations["updateMeal"];
        post?: never;
        /** Remove a meal and its food items */
        delete: operations["removeMeal"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coach/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get coach profile */
        get: operations["getProfile_1"];
        /**
         * Update coach profile
         * @description Only provided fields are updated (partial update)
         */
        put: operations["updateProfile"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get client by ID */
        get: operations["get_3"];
        /** Update client */
        put: operations["update_1"];
        post?: never;
        /** Delete client (soft delete) */
        delete: operations["delete_1"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meal-plans/{planId}/share/whatsapp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Share meal plan via WhatsApp
         * @description Sends the meal plan to the client's WhatsApp number
         */
        post: operations["shareViaWhatsApp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meal-plans/{planId}/days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a day (1–7) to a meal plan */
        post: operations["addDay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meal-plans/{planId}/days/{dayId}/meals": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a meal to a day */
        post: operations["addMeal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meal-plans/{planId}/days/{dayId}/meals/{mealId}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a food item to a meal (auto-calculates nutrition) */
        post: operations["addItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List clients
         * @description Returns all active clients for the authenticated coach. Filter by status using ?status=ACTIVE|ONBOARDING|INACTIVE
         */
        get: operations["list_1"];
        put?: never;
        /** Create client */
        post: operations["create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{clientId}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get full progress history
         * @description Returns all progress logs sorted by date descending
         */
        get: operations["getHistory_2"];
        put?: never;
        /**
         * Log progress
         * @description Creates or updates the progress entry for the given date (one per client per day)
         */
        post: operations["log"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{clientId}/progress/{logId}/photos": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List photos for a progress log
         * @description Returns all photos with pre-signed download URLs (valid 60 min)
         */
        get: operations["listPhotos"];
        put?: never;
        /**
         * Initiate photo upload
         * @description Saves a photo record and returns a pre-signed S3 URL for direct upload
         */
        post: operations["initiateUpload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{clientId}/meal-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all meal plans for a client */
        get: operations["list_2"];
        put?: never;
        /** Create meal plan for a client */
        post: operations["create_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{clientId}/check-ins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get check-in history
         * @description Returns all check-ins sorted by date descending
         */
        get: operations["getHistory_3"];
        put?: never;
        /**
         * Create check-in
         * @description Records a weekly check-in with adherence % against an active meal plan. One check-in per date.
         */
        post: operations["create_2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client-auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify client OTP
         * @description Verifies OTP for a client registered under the specified coach. Returns a CLIENT-role JWT.
         */
        post: operations["verifyOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/client-auth/otp/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send OTP to client
         * @description Sends a 6-digit OTP to the client's registered mobile number
         */
        post: operations["sendOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Razorpay webhook receiver
         * @description Handles subscription lifecycle events from Razorpay. No auth required — verified via HMAC-SHA256 signature.
         */
        post: operations["handleWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/subscribe": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Subscribe to a plan
         * @description Creates a Razorpay subscription and returns the checkout URL. Cancels any existing active subscription.
         */
        post: operations["subscribe"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Verify OTP
         * @description Verifies OTP and returns a JWT. Creates coach account on first login.
         */
        post: operations["verifyOtp_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/otp/send": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Send OTP
         * @description Sends a 6-digit OTP to the given Indian mobile number via SMS
         */
        post: operations["sendOtp_1"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/demo-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Demo login (dev only)
         * @description Bypasses OTP and issues a JWT directly. Only works when app.msg91.dev-mode=true. Returns 403 in production.
         */
        post: operations["demoLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/meal-plans/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Generate meal plan with AI
         * @description Submits an async GPT-4o job to generate a 7-day Indian meal plan for the given client. Poll GET /api/v1/ai/jobs/{id} for status.
         */
        post: operations["generate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meal-plans/{planId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update meal plan status (DRAFT → ACTIVE → COMPLETED → ARCHIVED) */
        patch: operations["updateStatus"];
        trace?: never;
    };
    "/api/v1/portal/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get my progress history
         * @description Returns all progress logs sorted by date descending
         */
        get: operations["getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portal/progress/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get my progress chart data
         * @description Returns progress logs for the last N days (default 30, max 90), sorted ascending for charting
         */
        get: operations["getChart"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portal/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get my profile
         * @description Returns the authenticated client's own profile
         */
        get: operations["getProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portal/meal-plans": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List my meal plans
         * @description Returns all meal plans assigned to the authenticated client
         */
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portal/meal-plans/{planId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get meal plan detail
         * @description Returns the full meal plan with all days, meals, and food items
         */
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/portal/check-ins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get my check-in history
         * @description Returns all check-ins sorted by date descending
         */
        get: operations["getHistory_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/food-items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Search food items
         * @description Search by name/Hindi name. Filter by cuisine type and/or category. Returns all items when no params are provided.
         */
        get: operations["search"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/food-items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get food item by ID */
        get: operations["get_2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/coach/dashboard": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get coach dashboard
         * @description Returns client counts by status, meal plan totals, clients needing a plan, and 5 most recent clients
         */
        get: operations["getDashboard"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{clientId}/progress/chart": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get progress chart data
         * @description Returns progress logs for the last N days (default 30, max 90), sorted ascending for charting
         */
        get: operations["getChart_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get billing status
         * @description Returns current subscription tier, status, and invoice history
         */
        get: operations["getStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ai/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Poll AI job status
         * @description Returns current status of an AI job. When COMPLETED, generatedMealPlanId is populated.
         */
        get: operations["getJob"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meal-plans/{planId}/days/{dayId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a day and all its meals from the plan */
        delete: operations["removeDay"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/meal-plans/{planId}/days/{dayId}/meals/{mealId}/items/{itemId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove a food item from a meal (auto-recalculates day totals) */
        delete: operations["removeItem"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/clients/{clientId}/progress/{logId}/photos/{photoId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a progress photo
         * @description Deletes the photo from S3 and removes the DB record
         */
        delete: operations["deletePhoto"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/billing/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Cancel subscription
         * @description Cancels the active subscription at the end of the current billing period
         */
        delete: operations["cancel"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        UpdateMealPlanRequest: {
            name?: string;
            description?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            /** Format: int32 */
            totalCaloriesTarget?: number;
        };
        ApiResponseMealPlanSummaryResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["MealPlanSummaryResponse"];
            errorCode?: string;
        };
        MealPlanSummaryResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            clientId?: string;
            name?: string;
            description?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            /** @enum {string} */
            status?: "DRAFT" | "ACTIVE" | "COMPLETED" | "ARCHIVED";
            aiGenerated?: boolean;
            /** Format: int32 */
            totalCaloriesTarget?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        LocalTime: {
            /** Format: int32 */
            hour?: number;
            /** Format: int32 */
            minute?: number;
            /** Format: int32 */
            second?: number;
            /** Format: int32 */
            nano?: number;
        };
        UpdateMealRequest: {
            /** @enum {string} */
            mealType?: "BREAKFAST" | "LUNCH" | "DINNER" | "SNACK" | "PRE_WORKOUT" | "POST_WORKOUT";
            name?: string;
            timeOfDay?: components["schemas"]["LocalTime"];
            /** Format: int32 */
            sequenceOrder?: number;
        };
        ApiResponseMealResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["MealResponse"];
            errorCode?: string;
        };
        MealItemResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            foodItemId?: string;
            foodItemName?: string;
            quantityGrams?: number;
            quantityUnit?: string;
            /** Format: int32 */
            calories?: number;
            proteinG?: number;
            carbsG?: number;
            fatG?: number;
        };
        MealResponse: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            mealType?: "BREAKFAST" | "LUNCH" | "DINNER" | "SNACK" | "PRE_WORKOUT" | "POST_WORKOUT";
            name?: string;
            timeOfDay?: components["schemas"]["LocalTime"];
            /** Format: int32 */
            sequenceOrder?: number;
            items?: components["schemas"]["MealItemResponse"][];
        };
        UpdateCoachRequest: {
            name?: string;
            email?: string;
            businessName?: string;
            gstin?: string;
        };
        ApiResponseCoachResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["CoachResponse"];
            errorCode?: string;
        };
        CoachResponse: {
            /** Format: uuid */
            id?: string;
            phone?: string;
            name?: string;
            email?: string;
            businessName?: string;
            gstin?: string;
            /** @enum {string} */
            subscriptionTier?: "STARTER" | "PROFESSIONAL" | "ENTERPRISE";
            /** @enum {string} */
            subscriptionStatus?: "TRIAL" | "ACTIVE" | "PAST_DUE" | "CANCELLED";
            /** Format: date-time */
            trialEndsAt?: string;
            /** Format: date-time */
            createdAt?: string;
        };
        UpdateClientRequest: {
            name?: string;
            email?: string;
            whatsappNumber?: string;
            /** Format: date */
            dateOfBirth?: string;
            /** @enum {string} */
            gender?: "MALE" | "FEMALE" | "OTHER";
            /** Format: int32 */
            heightCm?: number;
            weightKg?: number;
            /** @enum {string} */
            goal?: "WEIGHT_LOSS" | "WEIGHT_GAIN" | "MAINTENANCE" | "MUSCLE_GAIN";
            /** @enum {string} */
            dietaryPref?: "VEG" | "NON_VEG" | "VEGAN" | "JAIN" | "EGGETARIAN";
            /** @enum {string} */
            activityLevel?: "SEDENTARY" | "LIGHT" | "MODERATE" | "ACTIVE" | "VERY_ACTIVE";
            /** @enum {string} */
            status?: "ONBOARDING" | "ACTIVE" | "INACTIVE";
            healthConditions?: string[];
            allergies?: string[];
        };
        ApiResponseClientResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ClientResponse"];
            errorCode?: string;
        };
        ClientResponse: {
            /** Format: uuid */
            id?: string;
            phone?: string;
            name?: string;
            email?: string;
            whatsappNumber?: string;
            /** Format: date */
            dateOfBirth?: string;
            /** @enum {string} */
            gender?: "MALE" | "FEMALE" | "OTHER";
            /** Format: int32 */
            heightCm?: number;
            weightKg?: number;
            /** @enum {string} */
            goal?: "WEIGHT_LOSS" | "WEIGHT_GAIN" | "MAINTENANCE" | "MUSCLE_GAIN";
            /** @enum {string} */
            dietaryPref?: "VEG" | "NON_VEG" | "VEGAN" | "JAIN" | "EGGETARIAN";
            /** @enum {string} */
            activityLevel?: "SEDENTARY" | "LIGHT" | "MODERATE" | "ACTIVE" | "VERY_ACTIVE";
            healthConditions?: string[];
            allergies?: string[];
            /** @enum {string} */
            status?: "ONBOARDING" | "ACTIVE" | "INACTIVE";
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
        };
        ApiResponseVoid: {
            success?: boolean;
            message?: string;
            data?: Record<string, never>;
            errorCode?: string;
        };
        ApiResponseMealPlanDayResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["MealPlanDayResponse"];
            errorCode?: string;
        };
        MealPlanDayResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: int32 */
            dayNumber?: number;
            /** Format: int32 */
            totalCalories?: number;
            totalProteinG?: number;
            totalCarbsG?: number;
            totalFatG?: number;
            meals?: components["schemas"]["MealResponse"][];
        };
        AddMealRequest: {
            /** @enum {string} */
            mealType: "BREAKFAST" | "LUNCH" | "DINNER" | "SNACK" | "PRE_WORKOUT" | "POST_WORKOUT";
            name: string;
            timeOfDay?: components["schemas"]["LocalTime"];
            /** Format: int32 */
            sequenceOrder?: number;
        };
        AddMealItemRequest: {
            /** Format: uuid */
            foodItemId: string;
            quantityGrams: number;
            quantityUnit?: string;
        };
        ApiResponseMealItemResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["MealItemResponse"];
            errorCode?: string;
        };
        CreateClientRequest: {
            phone: string;
            name: string;
            email?: string;
            whatsappNumber?: string;
            /** Format: date */
            dateOfBirth?: string;
            /** @enum {string} */
            gender?: "MALE" | "FEMALE" | "OTHER";
            /** Format: int32 */
            heightCm?: number;
            weightKg?: number;
            /** @enum {string} */
            goal?: "WEIGHT_LOSS" | "WEIGHT_GAIN" | "MAINTENANCE" | "MUSCLE_GAIN";
            /** @enum {string} */
            dietaryPref?: "VEG" | "NON_VEG" | "VEGAN" | "JAIN" | "EGGETARIAN";
            /** @enum {string} */
            activityLevel?: "SEDENTARY" | "LIGHT" | "MODERATE" | "ACTIVE" | "VERY_ACTIVE";
            healthConditions?: string[];
            allergies?: string[];
        };
        LogProgressRequest: {
            /** Format: date */
            loggedDate: string;
            weightKg?: number;
            bodyFatPercent?: number;
            waistCm?: number;
            chestCm?: number;
            hipCm?: number;
            /** Format: int32 */
            adherencePercent?: number;
            notes?: string;
        };
        ApiResponseProgressLogResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ProgressLogResponse"];
            errorCode?: string;
        };
        ProgressLogResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            clientId?: string;
            /** Format: date */
            loggedDate?: string;
            weightKg?: number;
            bodyFatPercent?: number;
            waistCm?: number;
            chestCm?: number;
            hipCm?: number;
            /** Format: int32 */
            adherencePercent?: number;
            notes?: string;
        };
        InitiatePhotoUploadRequest: {
            photoType: string;
            contentType: string;
        };
        ApiResponsePhotoUploadResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PhotoUploadResponse"];
            errorCode?: string;
        };
        PhotoUploadResponse: {
            /** Format: uuid */
            photoId?: string;
            uploadUrl?: string;
            s3Key?: string;
            photoType?: string;
        };
        CreateMealPlanRequest: {
            name: string;
            description?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            /** Format: int32 */
            totalCaloriesTarget?: number;
        };
        CreateCheckInRequest: {
            /** Format: date */
            checkInDate: string;
            /** Format: uuid */
            mealPlanId: string;
            /** Format: int32 */
            adherencePercent?: number;
            clientNotes?: string;
            coachNotes?: string;
        };
        ApiResponseCheckInResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["CheckInResponse"];
            errorCode?: string;
        };
        CheckInResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            clientId?: string;
            /** Format: uuid */
            mealPlanId?: string;
            /** Format: date */
            checkInDate?: string;
            /** Format: int32 */
            adherencePercent?: number;
            clientNotes?: string;
            coachNotes?: string;
        };
        ClientVerifyOtpRequest: {
            phone: string;
            otp: string;
            /** Format: uuid */
            coachId: string;
        };
        ApiResponseClientAuthResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ClientAuthResponse"];
            errorCode?: string;
        };
        ClientAuthResponse: {
            token?: string;
            /** Format: uuid */
            clientId?: string;
            /** Format: uuid */
            coachId?: string;
            name?: string;
            phone?: string;
        };
        SendOtpRequest: {
            phone: string;
        };
        SubscribeRequest: {
            /** @enum {string} */
            planTier: "STARTER" | "PROFESSIONAL" | "ENTERPRISE";
        };
        ActiveSubscription: {
            /** Format: uuid */
            id?: string;
            /** @enum {string} */
            planTier?: "STARTER" | "PROFESSIONAL" | "ENTERPRISE";
            /** @enum {string} */
            subscriptionStatus?: "TRIAL" | "ACTIVE" | "PAST_DUE" | "CANCELLED";
            razorpaySubscriptionId?: string;
            checkoutUrl?: string;
            /** Format: date-time */
            currentPeriodStart?: string;
            /** Format: date-time */
            currentPeriodEnd?: string;
        };
        ApiResponseBillingStatusResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["BillingStatusResponse"];
            errorCode?: string;
        };
        BillingStatusResponse: {
            /** @enum {string} */
            tier?: "STARTER" | "PROFESSIONAL" | "ENTERPRISE";
            /** @enum {string} */
            status?: "TRIAL" | "ACTIVE" | "PAST_DUE" | "CANCELLED";
            /** Format: date-time */
            trialEndsAt?: string;
            activeSubscription?: components["schemas"]["ActiveSubscription"];
            invoices?: components["schemas"]["InvoiceSummary"][];
        };
        InvoiceSummary: {
            /** Format: uuid */
            id?: string;
            invoiceNumber?: string;
            /** Format: int32 */
            amountPaise?: number;
            /** Format: int32 */
            gstAmountPaise?: number;
            /** @enum {string} */
            status?: "PAID" | "PENDING" | "FAILED" | "REFUNDED";
            /** Format: date */
            invoiceDate?: string;
        };
        VerifyOtpRequest: {
            phone: string;
            otp: string;
            name?: string;
        };
        ApiResponseAuthResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AuthResponse"];
            errorCode?: string;
        };
        AuthResponse: {
            token?: string;
            /** Format: uuid */
            coachId?: string;
            phone?: string;
            name?: string;
            /** @enum {string} */
            subscriptionTier?: "STARTER" | "PROFESSIONAL" | "ENTERPRISE";
            /** @enum {string} */
            subscriptionStatus?: "TRIAL" | "ACTIVE" | "PAST_DUE" | "CANCELLED";
            isNewCoach?: boolean;
        };
        DemoLoginRequest: {
            phone: string;
            name?: string;
        };
        GenerateMealPlanRequest: {
            /** Format: uuid */
            clientId: string;
        };
        AiJobResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            clientId?: string;
            status?: string;
            jobType?: string;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            completedAt?: string;
            errorMessage?: string;
            /** Format: uuid */
            generatedMealPlanId?: string;
        };
        ApiResponseAiJobResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["AiJobResponse"];
            errorCode?: string;
        };
        ApiResponseListProgressLogResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ProgressLogResponse"][];
            errorCode?: string;
        };
        ApiResponseListMealPlanSummaryResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["MealPlanSummaryResponse"][];
            errorCode?: string;
        };
        ApiResponseMealPlanResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["MealPlanResponse"];
            errorCode?: string;
        };
        MealPlanResponse: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            clientId?: string;
            name?: string;
            description?: string;
            /** Format: date */
            startDate?: string;
            /** Format: date */
            endDate?: string;
            /** @enum {string} */
            status?: "DRAFT" | "ACTIVE" | "COMPLETED" | "ARCHIVED";
            aiGenerated?: boolean;
            /** Format: int32 */
            totalCaloriesTarget?: number;
            /** Format: date-time */
            createdAt?: string;
            /** Format: date-time */
            updatedAt?: string;
            days?: components["schemas"]["MealPlanDayResponse"][];
        };
        ApiResponseListCheckInResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["CheckInResponse"][];
            errorCode?: string;
        };
        ApiResponseListFoodItemResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["FoodItemResponse"][];
            errorCode?: string;
        };
        FoodItemResponse: {
            /** Format: uuid */
            id?: string;
            name?: string;
            nameHindi?: string;
            nameRegional?: string;
            /** @enum {string} */
            cuisineType?: "SOUTH_INDIAN" | "GUJARATI" | "PUNJABI" | "JAIN" | "BENGALI" | "RAJASTHANI" | "MAHARASHTRIAN" | "NORTH_EAST" | "PAN_INDIAN";
            /** @enum {string} */
            category?: "GRAIN" | "PROTEIN" | "VEGETABLE" | "FRUIT" | "DAIRY" | "FAT" | "BEVERAGE" | "SPICE" | "OTHER";
            caloriesPer100g?: number;
            proteinPer100g?: number;
            carbsPer100g?: number;
            fatPer100g?: number;
            fiberPer100g?: number;
            /** @enum {string} */
            source?: "IFCT" | "CUSTOM";
        };
        ApiResponseFoodItemResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["FoodItemResponse"];
            errorCode?: string;
        };
        ApiResponseDashboardResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["DashboardResponse"];
            errorCode?: string;
        };
        DashboardResponse: {
            /** Format: int64 */
            totalClients?: number;
            /** Format: int64 */
            activeClients?: number;
            /** Format: int64 */
            onboardingClients?: number;
            /** Format: int64 */
            inactiveClients?: number;
            /** Format: int64 */
            totalMealPlans?: number;
            /** Format: int64 */
            clientsNeedingPlan?: number;
            recentClients?: components["schemas"]["RecentClient"][];
        };
        RecentClient: {
            /** Format: uuid */
            id?: string;
            name?: string;
            phone?: string;
            status?: string;
        };
        ApiResponseListClientResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["ClientResponse"][];
            errorCode?: string;
        };
        ApiResponseListPhotoResponse: {
            success?: boolean;
            message?: string;
            data?: components["schemas"]["PhotoResponse"][];
            errorCode?: string;
        };
        PhotoResponse: {
            /** Format: uuid */
            id?: string;
            photoType?: string;
            downloadUrl?: string;
            /** Format: date-time */
            createdAt?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMealPlanResponse"];
                };
            };
        };
    };
    update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMealPlanRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMealPlanSummaryResponse"];
                };
            };
        };
    };
    delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    updateMeal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                dayId: string;
                mealId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMealRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMealResponse"];
                };
            };
        };
    };
    removeMeal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                dayId: string;
                mealId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    getProfile_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCoachResponse"];
                };
            };
        };
    };
    updateProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateCoachRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCoachResponse"];
                };
            };
        };
    };
    get_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseClientResponse"];
                };
            };
        };
    };
    update_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateClientRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseClientResponse"];
                };
            };
        };
    };
    delete_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    shareViaWhatsApp: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    addDay: {
        parameters: {
            query: {
                dayNumber: number;
            };
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMealPlanDayResponse"];
                };
            };
        };
    };
    addMeal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                dayId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMealRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMealResponse"];
                };
            };
        };
    };
    addItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                dayId: string;
                mealId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMealItemRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMealItemResponse"];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                status?: "ONBOARDING" | "ACTIVE" | "INACTIVE";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListClientResponse"];
                };
            };
        };
    };
    create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateClientRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseClientResponse"];
                };
            };
        };
    };
    getHistory_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListProgressLogResponse"];
                };
            };
        };
    };
    log: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LogProgressRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseProgressLogResponse"];
                };
            };
        };
    };
    listPhotos: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: string;
                logId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListPhotoResponse"];
                };
            };
        };
    };
    initiateUpload: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: string;
                logId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InitiatePhotoUploadRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponsePhotoUploadResponse"];
                };
            };
        };
    };
    list_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListMealPlanSummaryResponse"];
                };
            };
        };
    };
    create_1: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateMealPlanRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMealPlanSummaryResponse"];
                };
            };
        };
    };
    getHistory_3: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListCheckInResponse"];
                };
            };
        };
    };
    create_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCheckInRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseCheckInResponse"];
                };
            };
        };
    };
    verifyOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClientVerifyOtpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseClientAuthResponse"];
                };
            };
        };
    };
    sendOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendOtpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    handleWebhook: {
        parameters: {
            query?: never;
            header?: {
                "X-Razorpay-Signature"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": string;
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    subscribe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubscribeRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBillingStatusResponse"];
                };
            };
        };
    };
    verifyOtp_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VerifyOtpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAuthResponse"];
                };
            };
        };
    };
    sendOtp_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SendOtpRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    demoLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoLoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAuthResponse"];
                };
            };
        };
    };
    generate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateMealPlanRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAiJobResponse"];
                };
            };
        };
    };
    updateStatus: {
        parameters: {
            query: {
                status: "DRAFT" | "ACTIVE" | "COMPLETED" | "ARCHIVED";
            };
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMealPlanSummaryResponse"];
                };
            };
        };
    };
    getHistory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListProgressLogResponse"];
                };
            };
        };
    };
    getChart: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListProgressLogResponse"];
                };
            };
        };
    };
    getProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseClientResponse"];
                };
            };
        };
    };
    list: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListMealPlanSummaryResponse"];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseMealPlanResponse"];
                };
            };
        };
    };
    getHistory_1: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListCheckInResponse"];
                };
            };
        };
    };
    search: {
        parameters: {
            query?: {
                q?: string;
                cuisine?: "SOUTH_INDIAN" | "GUJARATI" | "PUNJABI" | "JAIN" | "BENGALI" | "RAJASTHANI" | "MAHARASHTRIAN" | "NORTH_EAST" | "PAN_INDIAN";
                category?: "GRAIN" | "PROTEIN" | "VEGETABLE" | "FRUIT" | "DAIRY" | "FAT" | "BEVERAGE" | "SPICE" | "OTHER";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListFoodItemResponse"];
                };
            };
        };
    };
    get_2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseFoodItemResponse"];
                };
            };
        };
    };
    getDashboard: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseDashboardResponse"];
                };
            };
        };
    };
    getChart_1: {
        parameters: {
            query?: {
                days?: number;
            };
            header?: never;
            path: {
                clientId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseListProgressLogResponse"];
                };
            };
        };
    };
    getStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBillingStatusResponse"];
                };
            };
        };
    };
    getJob: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseAiJobResponse"];
                };
            };
        };
    };
    removeDay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                dayId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    removeItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                planId: string;
                dayId: string;
                mealId: string;
                itemId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    deletePhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                clientId: string;
                logId: string;
                photoId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseVoid"];
                };
            };
        };
    };
    cancel: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["ApiResponseBillingStatusResponse"];
                };
            };
        };
    };
}
